spring.application.name=mapa-de-vagas

spring.datasource.url=jdbc:postgresql://localhost:5432/mapa_de_vagas
spring.datasource.username=mapa
spring.datasource.password=mapa

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false