spring.application.name=mapa-de-vagas

spring.datasource.url=jdbc:postgresql://localhost:5432/mapa_de_vagas
spring.datasource.username=mapa
spring.datasource.password=mapa

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=PT1H
app.cookie.secure=${COOKIE_SECURE:true}